# Starship prompt configuration
# https://starship.rs/config/
# Run `starship explain` to help dissect the current prompt
# ==============================================

# Timeout for slow commands (ms)
command_timeout = 1000

# Always start a new line before prompt
add_newline = true

# Define custom prompt layout
format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_state\
  $git_status\
  $package\
  $nodejs\
  $python\
  $rust\
  $jobs\
  $time\
  $character
"""

# Colors and style
[directory]
style = "cyan"
truncation_length = 3

[git_branch]
symbol = "ğŸŒ¿ "

[git_status]
style = "yellow"
conflicted = "âš¡"

[nodejs]
symbol = "â¬¢ "
format = "[$symbol$version]($style)"
style = "bold green"

[time]
format = "ğŸ•’ %H:%M:%S"
style = "green"

[character]
success_symbol = "â¯"
error_symbol = "â¯"
vicmd_symbol = "â®"
